config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :phone_number, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true, in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  # def set_restaurant
  #   @restaurant = Restaurant.find(params[:id])
  # end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      redirect_to restaurant_path(@restaurant), status: :unprocessable_entity
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <h1 class="text-center">Restaurants</h1>
    <div>
      <ul class="list-unstyled">
        <% @restaurants.each do |restaurant| %>
          <li><%= link_to restaurant.name, restaurant_path(restaurant), class: "text-decoration-none" %></li>
        <% end %>
      </ul>
    </div>
</div>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>
<%= simple_form_for [@restaurant] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>

  <%= f.submit "Submit restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
<div class="container">
  <h1>Restaurant</h1>
  <h2><%= @restaurant.name %></h2>
  <p><strong>Address: </strong><%= @restaurant.address %></p>
  <p><strong>Phone number: </strong> <%= @restaurant.phone_number %></p>
  <p><strong>Category: </strong> <%= @restaurant.category.capitalize %></p>
  <p><strong>Reviews</strong></p>
  <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item"><strong><%= review.rating %> out of 5</strong></li>
      <li class="list-group-item"><%= review.content %></li>
      <br>
    <% end %>
  </ul>
  <%= simple_form_for [@restaurant, @review] do |f| %>
  <br>
  <p><strong>Your review:</strong></p>
    <%= f.select :rating, [1, 2, 3, 4, 5] %>
    <%= f.input :content %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>
  <br>
  <%= link_to "Back to restaurants", restaurants_path, class: "text-decoration-none" %>
  <br>
  <br>
</div>

app/views/reviews/show.html.erb
<div class="container">
  <p><strong>Reviews</strong></p>
  <ul class="list-group">
  <%= @review.content %>
  <%= @review.rating %>
  </ul>
  <br>
</div>